export const DEFAULT_ENDPOINTS = {
    TEST_RESULTS: '/api/test-results'
};

export const ENV_VARS = {
    BASE_URL: 'DATA_ENGINE_BASE_URL',
    TOKEN_ENDPOINT: 'DATA_ENGINE_GENERATE_TOKEN',
    SERVICE_ACCOUNT: 'DATA_ENGINE_SERVICE_ACCOUNT',
    SERVICE_PASSWORD: 'DATA_ENGINE_SERVICE_PASSWORD',
    PROJECT_NAME: 'PROJECT_NAME',
    ENV: 'ENV',
    BUILD_ID: 'BUILD_BUILDID',
    SOURCE_VERSION: 'BUILD_SOURCEVERSION',
    SOURCE_BRANCH: 'BUILD_SOURCEBRANCH',
    // Azure DevOps specific vars
    TEAM_FOUNDATION_COLLECTION_URI: 'SYSTEM_TEAMFOUNDATIONCOLLECTIONURI',
    TEAM_PROJECT: 'SYSTEM_TEAMPROJECT'
};

export const PROVIDERS = {
    AZURE_DEVOPS: 'azure-devops'
};
